# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [2]:
import numpy as np

# Skapar matris A
A = np.arange(1, 16).reshape(3, 5)

# Skriver ut information om matrisen
print("Antal axlar (dimensioner):", A.ndim)
print("Form på matrisen:", A.shape)
print("Storlek (antal element):", A.size)
print("Datatyp för elementen:", A.dtype)


Antal axlar (dimensioner): 2
Form på matrisen: (3, 5)
Storlek (antal element): 15
Datatyp för elementen: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

In [4]:
import numpy as np

# Definierar matriserna B och C
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

# Elementvis subtraktion
elementwise_subtraction = B - C

# Elementvis multiplikation
elementwise_multiplication = B * C

# Matris-multiplikation
matrix_multiplication = B @ C

# Skriver ut resultaten
print("Matris B:")
print(B)
print("\nMatris C:")
print(C)
print("\nElementvis subtraktion (B - C):")
print(elementwise_subtraction)
print("\nElementvis multiplikation (B * C):")
print(elementwise_multiplication)
print("\nMatris-multiplikation (B @ C):")
print(matrix_multiplication)


Matris B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matris C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementvis subtraktion (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementvis multiplikation (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matris-multiplikation (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [55]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [59]:
B.min()

1

In [60]:
B.min(axis=0)

array([1, 2, 3])

In [61]:
B.argmin()

0

In [62]:
B.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [63]:
B.sum()

45

In [64]:
np.mean(B, axis=0)

array([4., 5., 6.])

In [65]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [57]:
print(A)

[[1 2]
 [2 4]]


In [58]:
A[1]

array([2, 4])

**Answer:**

In [ ]:
Det innebär att vi hämtar alla värden från de axlar där vi inte specificerade något index.

Eftersom vi inte specificerade något index för den andra axeln (kolumnerna), får vi tillbaka hela raden.

Vi får den andra raden eftersom vi använder index [1].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [67]:
A

array([[1, 2],
       [2, 4]])

In [66]:
for i in A:
    print(i)

[1 2]
[2 4]


In [68]:
for elemnet in np.nditer(A):
    print(elemnet)

1
2
2
4


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [70]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
Koden skapar först en array 
𝑎
a med 30 element, från 0 till 29, med hjälp av np.arange(30).

Sedan omformas 
𝑎
a till en ny array 
𝑏
b med tre axlar (dimensioner) med hjälp av reshape((2, 3, -1)). Det betyder att:

𝑏
b kommer att ha 2 "block" (första axeln),
Varje "block" har 3 rader (andra axeln),
Antalet kolumner (den tredje axeln) beräknas automatiskt av NumPy baserat på hur många element som finns kvar (i detta fall blir det 5 kolumner).
Så 
𝑏
b är en 3D-array med dimensionerna 
2
×
3
×
5
2×3×5.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [71]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [85]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [6]:
import numpy as np

def add_mult_matrices(mat1, mat2, operation):
    # Validate that the input are of type numpy.ndarray
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray")
    
    # Validate that the third argument is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'")
    
    if operation == 'add':
        # Validate that the matrices have the same size for addition
        if mat1.shape != mat2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        # Perform elementwise addition
        return mat1 + mat2
    
    elif operation == 'multiply':
        # Validate that the sizes conform for matrix multiplication
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError("For matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix")
        # Perform matrix multiplication
        return mat1 @ mat2

# Example usage
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

# Add the matrices
add_result = add_mult_matrices(B, C, 'add')

# Multiply the matrices
mult_result = add_mult_matrices(B, C, 'multiply')

print("Addition Result:")
print(add_result)

print("\nMultiplication Result:")
print(mult_result)


Addition Result:
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]

Multiplication Result:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [8]:
x = np.array([4,3])
x

array([4, 3])

In [9]:
5 * x

array([20, 15])

In [10]:
3 * x

array([12,  9])

In [11]:
5 * x + 3 * x

array([32, 24])

In [12]:
8 * x

array([32, 24])

In [13]:
4 * x - x

array([12,  9])

In [14]:
x.T

array([4, 3])

In [15]:
x.T.shape

(2,)

In [16]:
x + x.T

array([8, 6])

In [17]:
np.linalg.norm(x)

5.0

In [ ]:
10.1.2

In [18]:
v = np.array([3, 7, 0, 11])

In [19]:
dimension_v = v.shape[0]
print("Dimension of v:", dimension_v)

Dimension of v: 4


In [20]:
two_v = 2 * v
print("2v:", two_v)

2v: [ 6 14  0 22]


In [21]:
five_v = 5 * v
five_v_plus_two_v = five_v + two_v
print("5v + 2v:", five_v_plus_two_v)

5v + 2v: [21 49  0 77]


In [22]:
four_v = 4 * v
four_v_minus_two_v = four_v - two_v
print("4v - 2v:", four_v_minus_two_v)

4v - 2v: [ 6 14  0 22]


In [23]:
v_transpose = v.reshape(1, 4) 
print("Transpose of v (v^T):")
print(v_transpose)

Transpose of v (v^T):
[[ 3  7  0 11]]


In [24]:
norm_v = np.linalg.norm(v)
print("||v|| (Norm of v):", norm_v)

||v|| (Norm of v): 13.379088160259652


In [74]:
10.1.3

SyntaxError: invalid syntax (1926620562.py, line 1)

In [75]:
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

In [28]:
norm_v1 = np.linalg.norm(v1)
print("||v1|| (Norm of v1):", norm_v1)

||v1|| (Norm of v1): 7.14142842854285


In [27]:
v1_minus_v2 = v1 - v2
norm_v1_minus_v2 = np.linalg.norm(v1_minus_v2)
print("||v1 - v2|| (Norm of v1 - v2):", norm_v1_minus_v2)

||v1 - v2|| (Norm of v1 - v2): 4.47213595499958


In [ ]:
### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [30]:
import numpy as np


A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1, 2], [1, 2]])
I = np.array([[1, 0], [0, 1]])



In [31]:
two_A = 2 * A
print("2A:\n", two_A)


2A:
 [[ 4  2 -2]
 [ 2 -2  2]]


In [32]:
B_minus_2A = B - 2 * A
print("B - 2A:\n", B_minus_2A)


B - 2A:
 [[ 0 -4  3]
 [ 0 -2 -4]]


In [33]:
three_C_minus_two_E = 3 * C - 2 * E
print("3C - 2E:\n", three_C_minus_two_E)


3C - 2E:
 [[ 1  2]
 [ 4 -1]]


In [34]:
two_D_minus_three_C = 2 * D - 3 * C
print("2D - 3C:\n", two_D_minus_three_C)


2D - 3C:
 [[3 2]
 [2 3]]


In [38]:
D_T_plus_2D = D.T + 2 * D
print("D^T + 2D:\n", D_T_plus_2D)


D^T + 2D:
 [[ 9 12]
 [12  9]]


In [40]:
two_C_T_minus_two_D_T = 2 * C.T - 2 * D.T
print("2C^T - 2D^T:\n", two_C_T_minus_two_D_T)


2C^T - 2D^T:
 [[-4 -4]
 [-4 -4]]


In [80]:
A_T_minus_B = A.T - B
print("A^T - B:\n", A_T_minus_B)


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [76]:
np.dot(A, C)

array([[ 4,  7],
       [12, 17]])

In [43]:
CD = np.dot(C, D)
print("CD:\n", CD)


CD:
 [[11 10]
 [10 11]]


In [44]:
CB = np.dot(C, B)
print("CB:\n", CB)


CB:
 [[  8 -10  -3]
 [ 10  -8   0]]


In [45]:
CI = np.dot(C, I)
print("CI:\n", CI)


CI:
 [[1 2]
 [2 1]]


In [46]:
AB_T = np.dot(A, B.T)
print("AB^T:\n", AB_T)


AB^T:
 [[5 2]
 [7 4]]


In [ ]:
Uppgift 10.2.2

In [47]:
A = np.array([[2, 3, 4], [5, 4, 1]])


In [48]:
A_A_T = np.dot(A, A.T)
print("A * A^T:\n", A_A_T)

A * A^T:
 [[29 26]
 [26 42]]


In [ ]:
Uppgift 10.2.3

In [50]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [51]:
AB = np.dot(A, B)
AC = np.dot(A, C)

In [52]:
print("AB:\n", AB)
print("AC:\n", AC)

AB:
 [[ 4  7]
 [ 8 14]]
AC:
 [[ 4  7]
 [ 8 14]]


In [54]:
B_equals_C = np.array_equal(B, C)
print("Is B equal to C?", B_equals_C)


Is B equal to C? False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [81]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [82]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [83]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
Vi undersöker om v1 och v2 är en view eller en copy genom att använda .base-attributet.

Om .base returnerar None, betyder det att arrayen är en copy, men om .base returnerar den ursprungliga arrayen betyder det att det är en view.

När vi ändrar sista elementet i v2 till 123, ändras även sista elementet i v1 till 123.

Detta beror på att v2 är en view av v1 eftersom "basic indexing" skapar en view.

Det innebär att v2 och v1 delar samma underliggande data, så alla ändringar i v2 påverkar också direkt v1.